---
layout: cv
title: Carol Ashcraft CV
---
# Carol Ashcraft
BYU-Idaho Math Faculty in Academic Success and Tutoring Department

<div id="webaddress">
<a href="ashcraftc@byui.edu">ashcraftc@byui.edu</a>
| <a href="https://www.byui.edu/academic-success-and-tutoring/carol-ashcraft">Faculty Info page</a>
</div>


## Currently

Math Study Center Director and Faculty at BYU-Idaho

### Specialized in

Teaching, Mathematics, Tutor Training


### Research interests

Status, Self-Efficacy, Python, Machine Learning


## Education

`2013-2015`
__Brigham Young University, Provo UT__

- MA in Mathematics Education

`2007 - 2010`
__Brigham Young University - Idaho, Rexburg ID__

- BS in Mathematics Education

`2004 - 2007`
__Oakdale High School, Oakdale CA__




## Awards

`2021`
5 years of Service, *Brigham Young University Idaho*, Rexburg, Idaho




## Publications
Academic and Peer Status in the Mathematical Life Stories of Students

Wise, Carol Ann. Brigham Young University,  2015.

<div id="webaddress">
<a href="https://www.proquest.com/docview/2447002191?pq-origsite=gscholar&fromopenview=true&sourcetype=Dissertations%20&%20Theses">Accesible Here</a>
</div>

BYUI Math Tutor Training Website and materials

<div id="webaddress">
<a href="https://sites.google.com/byui.edu/new-math-tutor-training/home">Accesible Here</a>
</div>


## Occupation

`2016-present`
__Brigham University Idaho__, Rexburg, ID

- Math Faculty
- Math Study Center Director

`2015-2016`
__Utah Valley University__, Orem, UT

- Developmental math Faculty





<!-- ### Footer

Last updated: May 2013 -->